config/routes.rb
Concerts::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_scope :user do 
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end
  resources :events
  resources :sessions, only: [:new, :create, :destroy]

  root  'splash#homesplash'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/week',    to: 'week#home',            via: 'get'
  match '/month',   to: 'month#home',           via: 'get'
  patch "/bands/star"
  patch "/bands/unstar"
  patch "/bands/remove"
  match "/splash/emailsubmit", to: 'splash#emailsubmit', via: 'post'

end

app/models/band.rb
class Band < ActiveRecord::Base
end

app/models/emaillist.rb
class Emaillist < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
  self.primary_key = "event_id"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
         
  # Setup accessible (or protected) attributes for your model
  #attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  validates_presence_of :username
  
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
    end
  end
  
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end    
  
  def password_required?
    super && provider.blank?
  end
  
  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
  
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  self.primary_key = "venue_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :date_set
  before_filter :events_get
  before_action :configure_permitted_parameters, if: :devise_controller?

  def events_get
    @events = Event.find(:all)
  end
  
  def date_set
    @d = Date.today.at_beginning_of_week
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :username, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:login) { |u| u.permit({ roles: [] }, :username, :password) }
  end
  
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def star
    band = Band.find_by name: params[:name]
    rat = band.rating + 50
    band.update_attribute(:rating, rat)
  end
  
  def unstar
    band = Band.find_by name: params[:name]
    rat = band.rating - 50
    band.update_attribute(:rating, rat)
  end

  def remove
    band = Band.find_by name: params[:name]
    band.update_attribute(:rating, 0)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def show
  end
  
end

app/controllers/month_controller.rb
class MonthController < ApplicationController
  def home
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user =  User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "Logged in!"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
  alias_method :facebook, :all
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  layout false

  def homesplash
  end
  
  def emailsubmit
      @emaillist = Emaillist.new(:email => params[:email])
      @emaillist.save
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  #efore_action :correct_user,   only: [:edit, :update]
  #before_action :admin_user,     only: :destroy

  #def index
  #  @users = User.paginate(page: params[:page])
  #end

  #def show
  #  @user = User.find(params[:id])
  #end

  #def new
  #  @user = User.new
  #end

  #def edit
  #end

  #def update
  #  if @user.update_attributes(user_params)
  #    flash[:success] = "Profile updated"
  #    redirect_to @user
  #  else
  #    render 'edit'
  #  end
  #end

  #def create
  #  @user = User.new(user_params)
  #  if @user.save
  #    sign_in @user
  #    flash[:success] = "Welcome to Fisheye!"
  #    redirect_to @user
  #  else
  #    render 'new'
  #  end
  #end

  #def destroy
  #  User.find(params[:id]).destroy
  #  flash[:success] = "User deleted."
  #  redirect_to users_url
  #end


  #private

  #def user_params
  #  params.require(:user).permit(:name, :email, :password,
  #                               :password_confirmation)
  #end

  # Before filters

  #def signed_in_user
  #  unless signed_in?
  #    store_location
  #    redirect_to signin_url, notice: "Please sign in."
  #  end
  #end

  #def correct_user
  #  @user = User.find(params[:id])
  #  redirect_to(root_url) unless current_user?(@user)
  #end

  #def admin_user
  #  redirect_to(root_url) unless current_user.admin?
  #end
end

app/controllers/week_controller.rb
class WeekController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  #Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Sickday"
    if page_title.empty?
      base_title
    else
      "#{base_title}#{page_title}"
    end
  end
  
  def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

 # def sign_in(user)
 #   remember_token = User.new_remember_token
 #   cookies.permanent[:remember_token] = remember_token
 #   user.update_attribute(:remember_token, User.encrypt(remember_token))
 #   self.current_user = user
 # end
 
 # def signed_in?
 #   !current_user.nil?
 # end

 # def current_user=(user)
 #   @current_user = user
 # end

 # def current_user
 #   remember_token = User.encrypt(cookies[:remember_token])
 #   @current_user ||= User.find_by(remember_token: remember_token)
 # end

 # def current_user?(user)
 #  user == current_user
 # end

 # def sign_out
 #   self.current_user = nil
 #   cookies.delete(:remember_token)
 # end

 # def redirect_back_or(default)
 #   redirect_to(session[:return_to] || default)
 #   session.delete(:return_to)
 # end

 # def store_location
 #   session[:return_to] = request.url if request.get?
 # end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/bands/remove.html.erb
<h1>Bands#remove</h1>
<p>Find me in app/views/bands/remove.html.erb</p>

app/views/bands/star.html.erb
<h1>Bands#star</h1>
<p>Find me in app/views/bands/star.html.erb</p>

app/views/bands/unstar.html.erb
<h1>Bands#unstar</h1>
<p>Find me in app/views/bands/unstar.html.erb</p>

app/views/event_calendar/_day.html.erb
<div class="day">
	<h6 class="month">
		<%= @d.strftime("%^a") %>
	</h6>
	<h6>
		<%= @d.strftime("%b").upcase %>
		<%= @d.day %>
	</h6>
</div>

app/views/event_calendar/_event.html.erb
<% if @d >= Date.today %>
<div class="event <% if @d < Date.today %>old <%end%><%= @d %>">
	<!--<div class="<%#=@d%>loader overloader">
		<img src="/assets/ajax-loader.gif" style="margin-top:54px; margin-left:53px;">
	</div>
	-->
	<div class="playbutton"></div>
	<div class="bandpic" href="javascript:void(0);">
		<img class="topimg" src="">
	</div>
	
	<div class="event-full vis template">
		<div class="event-individual">
			<div class="star-empty mover" name="" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="" name="name"></div>
			<div class="curr-event"><h4></h4></div>
			<div class="deleter cross" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="" name="name"></div>
		</div>
	</div>
	
	<div class="littleinfo2 template-tiny"><h4 class="weektiny"></h4></div>
	
	<div class="event-individual2 template-secondary" id="">
			<div class="star-empty mover2" name="" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="" name="name"></div>
			<div class="curr-event2"><h4></h4></div>
			<div class="deleter cross" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="" name="name"></div>
	</div>
	
	<div class="venue-individual template-venue" id="">
			<div class="star-empty"></div>
			<div class="curr-venue"><h4></h4></div>
			<div class="cross"></div>
	</div>
	
	<div class="timeinfo template-time"><h4 class="timetiny"></h4></div>
	<div class="show-info template-info"><div class="info-button" id="" style:"float: right;"><h4><a class="linkinfo" href="">More Info</a></h4></div>
		
	</div>
</div>
<script>getEvents("<%= @d %>","<%= @d.tomorrow %>");</script>
<%end%>
<% @d=@d.tomorrow %>

app/views/event_calendar/_event2.html.erb
<div class="event <% if @d < Date.today %>old<%end%>">
	<div class="playbutton">
	</div>
	<% @eventstoday = @events.select{|x| x.eventtime.to_date == @d}.sort_by{|x| -(Band.find_by name: x.headliner).rating} %>
	<div class="bandpic" href="javascript:void(0);">
		<img class="topimg" src="<% if @eventstoday.length > 0 %><%= (Band.find_by name: (@eventstoday[0].headliner)).image %><% end %>">
	</div>
	<% @eventstoday.each_with_index do |individ, index| %>
		<% @currband = (Band.find_by name: individ.headliner[0,64]) %>
		
			<div class="event-full vis">
			<% individ.artists.each_with_index do |individ2, index2| %>
			<% @currband = (Band.find_by name: individ2[0,64]) %>
			
				<% if index2 == 0 %>
					<div class="event-individual <%= @currband.name.gsub(/[^0-9A-Za-z]/, '') %>" id="<%= Random.new.rand(10...100) %>">
						<% if @currband.rating > 50 %>
							<div class="star-full mover <% if index2 == 0 %>top<% end %>" name="<%= @currband.image %>" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="<%= @currband.name %>" name="name"></div>
						<% else %>
							<div class="star-empty mover <% if index2 == 0 %>top<% end %>" name="<%= @currband.image %>" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="<%= @currband.name %>" name="name"></div>
						<% end %>
					<div class="curr-event"><h4><%= individ2 %></h4></div>
					<div class="deleter cross" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="<%= individ.headliner%>" name="name"></div>
					</div>	
				<% else %>
					<div class="event-individual2 <%= @currband.name.gsub(/[^0-9A-Za-z]/, '') %>" id="<%= Random.new.rand(10...100) %>">
						<% if @currband.rating > 50 %>
							<div class="star-full mover2 <% if index2 == 0 %>top<% end %>" name="<%= @currband.image %>" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="<%= @currband.name %>" name="name"></div>
						<% else %>
							<div class="star-empty mover2 <% if index2 == 0 %>top<% end %>" name="<%= @currband.image %>" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="<%= @currband.name %>" name="name"></div>
						<% end %>
					<div class="curr-event2"><h4><%= individ2 %></h4></div>
					<div class="deleter cross" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="<%= individ.headliner%>" name="name"></div>
					</div>	
				<% end %>
				
			<% if index2 == 0 && index2 == individ.artists.size - 1 %>
				<div class="littleinfo2">
					<h4 class="weektiny">at</h4>
				</div>
			<% elsif index2 == 0 && !(index2 == individ.artists.size - 1) %>
				<div class="littleinfo2">
					<h4 class="weektiny">with</h4>
				</div>
			<% elsif index2 == individ.artists.size-1 && !(index2 == 0) %>
				<div class="littleinfo2">
					<h4 class="weektiny">at</h4>
				</div>
			<% else %>
				<div class="littleinfo2">
					<h4 class="weektiny">and</h4>
				</div>
			<% end %>
		<%end%>
			
			<% @currvenue = (Venue.find_by venue_id: individ.venue_id) %>
		
			<div class="event-individual2 <%= @currvenue.name.gsub(/[^0-9A-Za-z]/, '') %>" id="<%= @currvenue.venue_id %>">
				<div class="star-empty"></div>
				<div class="curr-venue"><h4><%= @currvenue.name %></h4></div>
				<div class="cross"></div>
			</div>
		
			<div class="littleinfo2">
				<h4 class="weektiny"><%= individ.eventtime.strftime("%I:%M%p") %></h4>
			</div>
			<div class="event-individual3">
				<div class="curr-venue2" id="<%= individ.id %>" style:"float: right;">SHOW INFO ></div>
			</div>
		</div>
	<%end%>		
	<% @d=@d.tomorrow %>
</div>

app/views/event_calendar/_week.html.erb
	<div class="container-week">
		<div class="container-event">
			<%= render 'event_calendar/day' %>
			<%= render 'event_calendar/event' %>
		</div>
		<div class="container-event">
			<%= render 'event_calendar/day' %>
			<%= render 'event_calendar/event' %>
		</div>
		<div class="container-event">
			<%= render 'event_calendar/day' %>
			<%= render 'event_calendar/event' %>
		</div>
		<div class="container-event">
			<%= render 'event_calendar/day' %>
			<%= render 'event_calendar/event' %>
		</div>
		<div class="container-event">
			<%= render 'event_calendar/day' %>
			<%= render 'event_calendar/event' %>
		</div>
		<div class="container-event">
			<%= render 'event_calendar/day' %>
			<%= render 'event_calendar/event' %>
		</div>
		<div class="container-event">
			<%= render 'event_calendar/day' %>
			<%= render 'event_calendar/event' %>
		</div>
	</div>

app/views/event_week/_event.html.erb
<% if @d >= Date.today %>
<div class="container-daily <%= @d %>">
	
	<div class="container-event template-big">
		<div class="event<% if @d < Date.today %> old<%end%>">
		
			<div class="playbutton"></div>
			<div class="bandpic" href="javascript:void(0);">
				<img class="topimg" src="">
			</div>
		
			<div class="event-individual" id="">
				<div class="star-empty mover2" name="" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="" name="name"></div>
				<div class="curr-event"><h4></h4></div>
				<div class="deleter cross" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="" name="name"></div>
			</div>	
		</div>
	</div>

	<div class="littleinfo template-tiny"><h4 class="weektiny"></h4></div>
		
	<div class="event-individual template-secondary" id="">
		<div class="star-empty mover2" name="" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="" name="name"></div>
		<div class="curr-event2"><h4></h4></div>
		<div class="deleter cross" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="" name="name"></div>
	</div>

	<div class="venue-individual2 template-venue" id="">
		<div class="star-empty"></div>
		<div class="curr-venue"><h4></h4></div>
		<div class="cross"></div>
	</div>
		
	<div class="timeinfo2 template-time"><h4 class="timetiny"></h4></div>
	<div class="show-info2 template-info"><div class="info-button" id="" style:"float: right;"><h4><a class="linkinfo" href="">More Info</a></h4></div>
</div>
</div>
<script>getWeekEvents("<%= @d %>","<%= @d.tomorrow %>");</script>

<%else%>
<div class="container-daily <%= @d %>">
</div>
<%end%>		
<% @d=@d.tomorrow %>

app/views/event_week/_event2.html.erb
<% @eventstoday = @events.select{|x| x.eventtime.to_date == @d}.sort_by{|x| -(Band.find_by name: x.headliner).rating} %>
<% @eventstoday.each_with_index do |individ, index2| %>
<div class="container-event">
	<div class="event <% if @d < Date.today %>old<%end%>">
		
		<div class="playbutton">
		</div>
		<div class="bandpic" href="javascript:void(0);">
			<img class="topimg" src="<% if @eventstoday.length > 0 %><%= (Band.find_by name: (individ.headliner)).image %><% end %>">
		</div>
			
		<% individ.artists.each_with_index do |individ2, index| %>
			<% @currband = (Band.find_by name: individ2) %>
				<div class="event-individual <%= @currband.name.gsub(/[^0-9A-Za-z]/, '') %>" id="<%= Random.new.rand(10...100) %>">
					<% if @currband.rating > 50 %>
						<div class="star-full mover2 <% if index == 0 %>top<% end %>" name="<%= @currband.image %>" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="<%= @currband.name %>" name="name"></div>
					<% else %>
						<div class="star-empty mover2 <% if index == 0 %>top<% end %>" name="<%= @currband.image %>" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="<%= @currband.name %>" name="name"></div>
					<% end %>
				<div class="curr-event"><h4><%= individ2 %></h4></div>
				<div class="deleter cross" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="<%= individ.headliner%>" name="name"></div>
				</div>	
			
			<% if index == 0 && index == individ.artists.size - 1 %>
				<div class="littleinfo">
					<h4 class="weektiny">at</h4>
				</div>
			<% elsif index == 0 && !(index == individ.artists.size - 1) %>
				<div class="littleinfo">
					<h4 class="weektiny">with</h4>
				</div>
			<% elsif index == individ.artists.size-1 && !(index == 0) %>
				<div class="littleinfo">
					<h4 class="weektiny">at</h4>
				</div>
			<% else %>
				<div class="littleinfo">
					<h4 class="weektiny">and</h4>
				</div>
			<% end %>
		<% end %>
		
		<% @currvenue = (Venue.find_by venue_id: individ.venue_id) %>
		
		<div class="event-individual <%= @currvenue.name.gsub(/[^0-9A-Za-z]/, '') %>" id="<%= @currvenue.venue_id %>">
			<div class="star-empty"></div>
			<div class="curr-venue"><h4><%= @currvenue.name %></h4></div>
			<div class="cross"></div>
		</div>
		
		<div class="littleinfo">
			<h4 class="weektiny"><%= individ.eventtime.strftime("%I:%M%p") %></h4>
		</div>
	</div>
</div>
<%end%>		
<% @d=@d.tomorrow %>

app/views/events/remove.html.erb
<h1>Events#remove</h1>
<p>Find me in app/views/events/remove.html.erb</p>

app/views/events/show2.html.erb
<% provide(:title, 'Test Event') %>

<#%= @currband = Band.find_by name: @event.headliner %>

<div class="secondary-header2">
	<%= render 'layouts/navbar3' %>
</div>

<div class="container-moreinfo">
	<div class="moreinfo-top moreinfo-top-template">
		<div class="part5 midspace template5">
			<div class="part5sub template5sub">
			<div class="part1">
				<div class="event-individual" id="">
					<div class="star-empty mover2" name="" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="" name="name"></div>
					<div class="curr-event"><h4></h4></div>
					<div class="deleter cross" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="" name="name"></div>
				</div>	
			</div>
			
			<div class="part2 bandpicture">
				<div class="bandpic"><img src="" class="picture" \></div>
			</div>
			
			<div class="part2 songs">
				<div class="toptracks">
					<div class="title">
						<h4 class="bump">Top Tracks</h4>
					</div>
					<div class="songdetails">
						<div class="song-individual">
							<div class="songname"><h4 class="bump">Test Song</h4></div>
							<div class="currsong short">
								<div class="youtube2" name="https://www.youtube.com/embed/vjncyiuwwXQ"></div>
								<div class="soundcloud2"></div>
								<div class="rdio2"></div>
								<div class="spotify2"></div>
							</div>
						</div>
						<div class="song-individual">
							<div class="songname"><h4 class="bump">Test Song #2</h4></div>
							<div class="currsong short">
								<div class="youtube2" name="https://www.youtube.com/embed/6h9XUYj96ho"></div>
								<div class="soundcloud2"></div>
								<div class="rdio2"></div>
								<div class="spotify2"></div>
							</div>
						</div>
						<div class="song-individual">
							<div class="songname"><h4 class="bump">Test Song #3</h4></div>
							<div class="currsong short">
								<div class="youtube2" name="https://www.youtube.com/embed/5NmjJeNFUVU"></div>
								<div class="soundcloud2"></div>
								<div class="rdio2"></div>
								<div class="spotify2"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
			</div>
			
		</div>
		<div class="part1 eventinfo">
			<div class="event-individual bigspace">
				<div class="price"><a href=""><h4 class="leftbump"></h4></a></div>
				<div class="curr-seller"><a href=""><h4 class="rightbump"></h4></a></div>
			</div>
			
			<div class="event-individual titleevent bigspace2">
					<div class="star-empty mover2" name="" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="" name="name"></div>
					<div class="curr-event"><h4></h4></div>
					<div class="deleter cross" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="" name="name"></div>
			</div>	
			
			<div class="time">
				<h4 class="date less"></h4>
				<h4 class="showtime"></h4>
			</div>
			
			<div class="event-individual titlevenue bigspace2">
					<div class="star-empty mover2" name="" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="" name="name"></div>
					<div class="curr-venue"><a href=""><h4></h4></a></div>
					<div class="deleter cross" href="javascript:void(0);"><input name="_method" type="hidden" value="patch" /><input type="hidden" value="" name="name"></div>
			</div>
			
			<div class="address">
				<h4 class="address1 less"></h4>
				<h4 class="address2"></h4>
			</div>
		</div>
		<div class="part1 social">
			Social bars
		</div>
	</div>
	
	<div class="moreinfo-bottom moreinfo-bottom-template">
		<div class="part3">
			<h5>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque faucibus nulla a magna viverra, eget luctus justo placerat. Donec non congue turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sit amet consequat augue, ut condimentum sem. Etiam eros elit, eleifend eu quam sit amet, cursus euismod purus. Cras dolor nisl, posuere in auctor lobortis, mattis eget dui. Proin auctor, dui vel posuere lobortis, augue diam interdum erat, lacinia congue orci nulla id tortor. Integer gravida tempor sapien, eu adipiscing odio luctus ut.
			</h5>
		</div>
		<div class="part4"><iframe width="100%" height="234" frameborder="0" style="border:0" src=""></iframe></div>
	</div>
</div>

<script>getDayEvents(<%= params[:id] %>)</script>

app/views/events/star.html.erb
<h1>Events#star</h1>
<p>Find me in app/views/events/star.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://limitless-taiga-3101.herokuapp.com/">Concert</a>
    Scheduling Application
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sickday.at", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_mover.html.erb
<script>
window.onload = function() {
	$('.mover').on('click',function () {
        $(this).closest('.event-individual').insertAfter($(this).closest('.event'));
    });
};
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>Just some stuff about us.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>You can find us around the local mall</p>